# CI Script used for ABP iOS

variables:
  GIT_STRATEGY: clone

stages:
  - test

cache:
  paths:
    - Carthage

build_code:
  stage: test
  before_script:
    - killall "Simulator" 2> /dev/null; xcrun simctl erase all
    - cp ~/Desktop/ABP-Secret-API-Env-Vars.sh $CI_PROJECT_DIR
    - carthage update --platform ios --no-use-binaries --cache-builds
  script:
    - set -o pipefail && xcodebuild clean test -project AdblockPlusSafari.xcodeproj -scheme AdblockPlusSafari -destination 'platform=iOS Simulator,name=iPhone X,OS=11.3' -skip-testing:AdblockPlusSafariTests/ContentBlockerTests/testReloadContentBlocker
    - set -o pipefail && xcodebuild clean test -project AdblockPlusSafari.xcodeproj -scheme AdblockPlusSafari -destination 'platform=iOS Simulator,name=iPhone SE,OS=10.3.1' -skip-testing:AdblockPlusSafariTests/ContentBlockerTests/testReloadContentBlocker
    - set -o pipefail && xcodebuild clean test -project AdblockPlusSafari.xcodeproj -scheme AdblockPlusSafari -destination 'platform=iOS Simulator,name=iPhone 6s Plus,OS=9.3' -skip-testing:AdblockPlusSafariTests/ContentBlockerTests/testReloadContentBlocker
  tags:
    - ios, abp