# CI Script used for ABP iOS

stages:
  - build

build_code:
  stage: build
  script:
    - set -o pipefail && xcodebuild clean test -project AdblockPlusSafari.xcodeproj -scheme AdblockPlusSafari -destination 'platform=iOS Simulator,name=iPhone X,OS=11.3'
    - set -o pipefail && xcodebuild clean test -project AdblockPlusSafari.xcodeproj -scheme AdblockPlusSafari -destination 'platform=iOS Simulator,name=iPhone SE,OS=10.3.1'
    - set -o pipefail && xcodebuild clean test -project AdblockPlusSafari.xcodeproj -scheme AdblockPlusSafari -destination 'platform=iOS Simulator,name=iPhone 6s Plus,OS=9.3'
    - set -o pipefail && xcodebuild clean test -project AdblockPlusSafari.xcodeproj -scheme libadblockplus-ios -destination 'platform=iOS Simulator,name=iPhone X,OS=11.3'
    - set -o pipefail && xcodebuild clean test -project AdblockPlusSafari.xcodeproj -scheme libadblockplus-ios -destination 'platform=iOS Simulator,name=iPhone SE,OS=10.3.1'
    - set -o pipefail && xcodebuild clean test -project AdblockPlusSafari.xcodeproj -scheme libadblockplus-ios -destination 'platform=iOS Simulator,name=iPhone 6s Plus,OS=9.3'
  tags:
    - ios, abp